# Generated by Django 2.0.4 on 2018-04-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.IntegerField(choices=[(1, 'Студент'), (0, 'Преподаватель'), (2, 'Аспирант')], default=1, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
